### ISSUE TITLE
Don't use #!/usr/bin/env bash

### ISSUE THREAD

**Issue by 71zenith** [zim0369/gelacritty#1]
The script is quite nice. I don't use alacritty that often(have kept it as an backup terminal). It sure helped me to learn a lot about shell scripting. I would recommend you to  use #!/bin/sh cause the script is POSIX compliant and there is no need to make bash an forceful dependency when it's not needed.

**Comment by zim0369** [comment]
`bash --posix gela` works fine.

Thanks! I'll update.
